import enum

class Piece(enum.Enum):
    e_O = ...
    e_X = ...

class GameState(enum.Enum):
    e_InPlay = ...
    e_OWon = ...
    e_XWon = ...
    e_Draw = ...

class Location:
    def __init__(self, row: int, col: int) -> None: ...

class Board:
    def moveX(self, location: Location) -> int: ...
    def moveO(self, location: Location) -> int: ...
    def state(self) -> GameState: ...
    def board(self) -> list[list[Piece | None]]: ...
    def clear(self, location: Location) -> None: ...
